### ISSUE TITLE
Bug: selecting debug configuration opens new buffer with selection as name

### ISSUE THREAD

**Issue by eyev0** [nvim-telescope/telescope-dap.nvim#12]
nvim version: NVIM v0.7.0-dev+1313-g3b28bd57f
telescope: cf2d6d34282afd90f0f5d2aba265a23b068494c2 (latest as of now)

This happens due to `actions.select_default:replace` does not actually replace default action

**Comment by Conni2461** [comment]
That shouldnt happen. This might be a bug in telescope. `select_default:replace` has to work! I cant test right now because i am on my phone. I will investigate later.

**Comment by Conni2461** [comment]
can't reproduce. I tried `Telescope git_branches` and that works just fine and uses `select_default:replace`
https://github.com/nvim-telescope/telescope.nvim/blob/cf2d6d34282afd90f0f5d2aba265a23b068494c2/lua/telescope/builtin/git.lua#L286

**Comment by Conni2461** [comment]
dup of https://github.com/nvim-telescope/telescope.nvim/issues/1809
