### ISSUE TITLE
Override of dap.ui.pick_one conflicts with nvim-dap 0.8.0

### ISSUE THREAD

**Issue by MimeLyc** [nvim-telescope/telescope-dap.nvim#23]
Hi, tks u for the plugin and it helps me a lot.

I encountered this problem after upgrading nvim-dap to 0.8.0. ⬇️
[version 0\.8\.0 with plugins telescope/telescope\-ui/nvim\-dap\-go unable to run processId at correct time\. · Issue \#1258 · mfussenegger/nvim\-dap](https://github.com/mfussenegger/nvim-dap/issues/1258)

Is there any plan to resolve this conflict, or how can I make this plugin work with the latest nvim-dap?

**Comment by ancientjpeg** [comment]
Noticing the same issue — getting a crashing stack trace due to a null `cb` (see #25). Have you found a fix on your end?

**Comment by ancientjpeg** [comment]
I've temporarily fixed this on my end by coercing `nvim-dap` to point to the `0.7.0` tag. @trevorwhitney @rossjaywill hopefully that'll work for you too.
