### ISSUE TITLE
Picker Fails When Attempting To Attach

### ISSUE THREAD

**Issue by ancientjpeg** [nvim-telescope/telescope-dap.nvim#25]
I'm experiencing a bug right now where `dap` appears to fail on attach, but the error message appears to be coming form this plugin. Here's the stack trace I'm being given:

```
E5108: Error executing lua: ...azy/telescope-dap.nvim/lua/telescope/_extensions/dap.lua:260: attempt to call upvalue 'cb' (a nil value)
stack traceback:
        ...azy/telescope-dap.nvim/lua/telescope/_extensions/dap.lua:260: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>
```

This happens with multiple different applications. I have yet to verify if this is a bad PID being passed, but it doesn't seem like it.

Let me know if you need any other information!

**Comment by trevorwhitney** [comment]
bump. seeing the same problem

**Comment by rossjaywill** [comment]
Seeing the same here, I've tried pinning telescope, nvim-dap, and telescope-dap back to previous commits.
No luck yet.

**Comment by ancientjpeg** [comment]
@trevorwhitney @rossjaywill After reading through the issues/open PRs, I believe this is a duplicate of #23. We should probably continue discussion on that thread.
